"""configuration app_name

Revision ID: 0cac32f1f8df
Revises: 3f97aac56702
Create Date: 2024-05-22 16:54:03.250886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cac32f1f8df'
down_revision: Union[str, None] = '3f97aac56702'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('configuration', sa.Column('telegram_grabber_app_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('configuration', 'telegram_grabber_app_name')
    # ### end Alembic commands ###
